"""Initial migration

Revision ID: 856cbd716f90
Revises: cc3d4a9f4da6
Create Date: 2025-02-02 00:04:54.112554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '856cbd716f90'
down_revision: Union[str, None] = 'cc3d4a9f4da6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
